"""create scholarship matching tables

Revision ID: 603848a52d5b
Revises: 6e1035fe0cc6
Create Date: 2026-09-07 03:28:00.314497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '603848a52d5b'
down_revision: Union[str, Sequence[str], None] = '6e1035fe0cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('intake', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_university_id'), 'programs', ['university_id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('university_id', sa.UUID(), nullable=True),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('degree_level', sa.Enum('BS', 'MS', 'PHD', 'OTHER', name='scholarship_degree_level', native_enum=False), nullable=True),
    sa.Column('funding_status', sa.Enum('FULLY_FUNDED', 'SUBSTANTIALLY_FUNDED', 'PARTIALLY_FUNDED', 'TUITION_ONLY', 'STIPEND_ONLY', 'OTHER_COMBINATION', 'UNKNOWN', name='funding_status', native_enum=False), nullable=False),
    sa.Column('intake', sa.String(), nullable=True),
    sa.Column('application_fee', sa.String(), nullable=True),
    sa.Column('application_method', sa.String(), nullable=True),
    sa.Column('application_procedure', sa.Text(), nullable=True),
    sa.Column('official_scholarship_url', sa.String(), nullable=False),
    sa.Column('official_application_url', sa.String(), nullable=True),
    sa.Column('lifecycle_status', sa.Enum('NEWLY_DISCOVERED', 'VERIFIED', 'UNVERIFIED', 'UPDATED', 'EXPIRED', 'CLOSED', 'REOPENED', 'STALE', 'SOURCE_UNAVAILABLE', name='lifecycle_status', native_enum=False), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('closing_status', sa.String(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'CONFLICTING', name='scholarship_verification_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('tuition_coverage', sa.String(), nullable=True),
    sa.Column('tuition_amount_or_pct', sa.String(), nullable=True),
    sa.Column('stipend', sa.String(), nullable=True),
    sa.Column('accommodation', sa.String(), nullable=True),
    sa.Column('travel_airfare', sa.String(), nullable=True),
    sa.Column('health_insurance', sa.String(), nullable=True),
    sa.Column('visa_support', sa.String(), nullable=True),
    sa.Column('family_dependent_benefits', sa.String(), nullable=True),
    sa.Column('spouse_allowed', sa.Boolean(), nullable=True),
    sa.Column('dependent_policy', sa.Text(), nullable=True),
    sa.Column('value_status', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_details_scholarship_id'), 'funding_details', ['scholarship_id'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('eligibility_verdict', sa.Enum('ELIGIBLE', 'LIKELY', 'POSSIBLY', 'NOT', 'UNKNOWN_REQUIRES_VERIFICATION', name='eligibility_verdict', native_enum=False), nullable=False),
    sa.Column('match_strength', sa.Enum('STRONG', 'POSSIBLE', 'NOT', name='match_strength', native_enum=False), nullable=False),
    sa.Column('hard_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('soft_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions_triggered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failed_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unverified_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remaining_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_scholarship_id'), 'matches', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ELIGIBILITY', 'ACADEMIC', 'GPA', 'LANGUAGE', 'TEST', 'AGE', 'EXPERIENCE', 'NATIONALITY', 'RESEARCH', 'OTHER', name='requirement_category', native_enum=False), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('value_status', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_scholarship_id'), 'requirements', ['scholarship_id'], unique=False)
    op.create_table('scholarship_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_status', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_fields_scholarship_id'), 'scholarship_fields', ['scholarship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_fields_scholarship_id'), table_name='scholarship_fields')
    op.drop_table('scholarship_fields')
    op.drop_index(op.f('ix_requirements_scholarship_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_scholarship_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_funding_details_scholarship_id'), table_name='funding_details')
    op.drop_table('funding_details')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_programs_university_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('universities')
    # ### end Alembic commands ###
