"""create profile tables

Revision ID: 6e1035fe0cc6
Revises: fed0167c65c9
Create Date: 2026-09-07 03:26:06.124847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e1035fe0cc6'
down_revision: Union[str, Sequence[str], None] = 'fed0167c65c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('country_of_residence', sa.String(), nullable=True),
    sa.Column('current_degree', sa.String(), nullable=True),
    sa.Column('target_degree_level', sa.Enum('BS', 'MS', 'PHD', 'OTHER', name='degree_level', native_enum=False), nullable=True),
    sa.Column('target_fields', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('target_countries', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('education_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('gpa', sa.Numeric(), nullable=True),
    sa.Column('gpa_scale', sa.Numeric(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_records_profile_id'), 'education_records', ['profile_id'], unique=False)
    op.create_table('experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('WORK', 'RESEARCH', 'PUBLICATION', 'PROJECT', name='experience_kind', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_profile_id'), 'experience', ['profile_id'], unique=False)
    op.create_table('missing_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missing_info_profile_id'), 'missing_info', ['profile_id'], unique=False)
    op.create_table('profile_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.Enum('DEGREE', 'FUNDING', 'FIELD', 'COUNTRY', 'NATIONALITY', 'LANGUAGE', 'TEST', 'GPA', 'SPOUSE_DEPENDENT', 'OTHER', name='criterion_dimension', native_enum=False), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kind', sa.Enum('HARD_CONSTRAINT', 'SOFT_PREFERENCE', 'EXCLUSION', name='criterion_kind', native_enum=False), nullable=False),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_criteria_profile_id'), 'profile_criteria', ['profile_id'], unique=False)
    op.create_table('test_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.Enum('IELTS', 'TOEFL', 'PTE', 'GRE', 'GMAT', 'OTHER', name='test_type', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('HAVE', 'PLANNED', 'NONE', name='test_status', native_enum=False), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('taken_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scores_profile_id'), 'test_scores', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_scores_profile_id'), table_name='test_scores')
    op.drop_table('test_scores')
    op.drop_index(op.f('ix_profile_criteria_profile_id'), table_name='profile_criteria')
    op.drop_table('profile_criteria')
    op.drop_index(op.f('ix_missing_info_profile_id'), table_name='missing_info')
    op.drop_table('missing_info')
    op.drop_index(op.f('ix_experience_profile_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_education_records_profile_id'), table_name='education_records')
    op.drop_table('education_records')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
