"""create application planning tables

Revision ID: ad4826bd57e6
Revises: b53c6b5689ba
Create Date: 2026-09-21 02:03:35.933183

Creates `tasks` and `submission_approvals` (Phase 4/T118-T119, data-model.md
§8-§9) on top of the existing `applications` table. Additive only — no
column is dropped or altered on any existing table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4826bd57e6'
down_revision: Union[str, Sequence[str], None] = 'b53c6b5689ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('submission_scope', sa.String(), nullable=False),
    sa.Column('content_fingerprint', sa.String(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_approvals_application_id'), 'submission_approvals', ['application_id'], unique=False)
    op.create_index(op.f('ix_submission_approvals_approved_by'), 'submission_approvals', ['approved_by'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('readiness_label', sa.Enum('COMPLETE', 'MISSING', 'USER_MUST_OBTAIN', 'AI_CAN_GENERATE', 'NEEDS_HUMAN_REVIEW', 'NEEDS_OFFICIAL_VERIFICATION', name='task_readiness_label', native_enum=False), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_application_id'), 'tasks', ['application_id'], unique=False)
    op.create_index(op.f('ix_tasks_requirement_id'), 'tasks', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_requirement_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_application_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_submission_approvals_approved_by'), table_name='submission_approvals')
    op.drop_index(op.f('ix_submission_approvals_application_id'), table_name='submission_approvals')
    op.drop_table('submission_approvals')
    # ### end Alembic commands ###
