"""create source registry tables

Revision ID: d501fadbb3f1
Revises: 603848a52d5b
Create Date: 2026-09-08 01:55:23.808939

Creates source_registry, candidate_sources, source_fetch_log, and
scholarship_sources (Blueprint §14, §29, §33). These tables are
system-owned, not user-owned: sources are curated/approved by operators,
not scoped per end-user, so none of them carry a `user_id` column.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd501fadbb3f1'
down_revision: Union[str, Sequence[str], None] = '603848a52d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('source_type', sa.Enum('GOV', 'NATIONAL_EDUCATION', 'UNIVERSITY', 'DEPARTMENT', 'PROVIDER', 'FOUNDATION', 'NGO', 'EMBASSY', 'INTERNATIONAL_ORG', 'RESEARCH', 'API', 'APPROVED_AGGREGATOR', name='source_type', native_enum=False), nullable=False),
    sa.Column('official_status', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('access_method', sa.Enum('API', 'MCP', 'WEB', name='access_method', native_enum=False), nullable=False),
    sa.Column('discovery_role', sa.Boolean(), nullable=False),
    sa.Column('verification_role', sa.Boolean(), nullable=False),
    sa.Column('reliability_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='reliability_level', native_enum=False), nullable=False),
    sa.Column('update_frequency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'DISABLED', 'FAILING', name='source_status', native_enum=False), nullable=False),
    sa.Column('extraction_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_registry_domain'), 'source_registry', ['domain'], unique=True)
    op.create_table('candidate_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discovered_from', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('proposed_type', sa.Enum('GOV', 'NATIONAL_EDUCATION', 'UNIVERSITY', 'DEPARTMENT', 'PROVIDER', 'FOUNDATION', 'NGO', 'EMBASSY', 'INTERNATIONAL_ORG', 'RESEARCH', 'API', 'APPROVED_AGGREGATOR', name='source_type', native_enum=False), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='candidate_source_status', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_fetch_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('OK', 'FAIL', 'TIMEOUT', name='fetch_status', native_enum=False), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_fetch_log_source_id'), 'source_fetch_log', ['source_id'], unique=False)
    op.create_table('scholarship_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'UNVERIFIED', 'CONFLICTING', name='scholarship_source_verification_status', native_enum=False), nullable=False),
    sa.Column('reliability', sa.String(), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_sources_scholarship_id'), 'scholarship_sources', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_scholarship_sources_source_id'), 'scholarship_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_sources_source_id'), table_name='scholarship_sources')
    op.drop_index(op.f('ix_scholarship_sources_scholarship_id'), table_name='scholarship_sources')
    op.drop_table('scholarship_sources')
    op.drop_index(op.f('ix_source_fetch_log_source_id'), table_name='source_fetch_log')
    op.drop_table('source_fetch_log')
    op.drop_table('candidate_sources')
    op.drop_index(op.f('ix_source_registry_domain'), table_name='source_registry')
    op.drop_table('source_registry')
    # ### end Alembic commands ###
